name: Bug Report
description: File a bug report
labels: ["bug"]
body:
  - type: textarea
    id: what-happened
    attributes:
      label: Describe The Bug
      description: A clear and concise description of what the bug is.
    validations:
      required: false
  - type: textarea
    id: reproduction-steps
    attributes:
      label: To Reproduce
      description: "Steps to reproduce the behavior:"
      placeholder: |
       1. Go to...
       2. Click on....
       3. Scroll down to....
       4. See error
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem.