name: Documentation

on:
  push:
    branches: [main]

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: Yarn
        run: npm install -g yarn
      - name: Install
        run: yarn install
      - name: Deploy docs
        run: |
          git config --global user.name 'venatbot'
          git config --global user.email 'venatbot@protonmail.com'
          git remote set-url origin 'https://venatbot:${{ secrets.GH_TOKEN }}@github.com/the-convocation/twitter-scraper.git'
          yarn docs:deploy