# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [16.x]
    steps:
      - uses: actions/checkout@v3
      - name: Install Node.js ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - name: Yarn
        run: npm install -g yarn
      - name: Install
        run: yarn install
      - name: Git Submodule Update
        run: |
          git submodule update --init --recursive
      - name: Build
        run: yarn build